# Site settings
title: Alexandra Greenspan
email: alexandra.greenspan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio and Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexsg.com" # the base hostname & protocol for your site
twitter_username: polarwishes
github_username:  alexsg

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

paginate: 5
paginate_path: "/blog/page/:num/"

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "pretty"